version: '3'
services:
  discovery:
    image: kobzonera/eureka-service
    restart: always
    ports:
      - 8761:8761
  gateway-service:
    image: kobzonera/gateway-service
    restart: always
    ports:
      - 8080:8080
  eureka-client:
    image: kobzonera/eureka-client
    restart: always
    ports:
      - 8082:8082
  feign-client:
    image: kobzonera/feign-client
    restart: always
    ports:
      - 8083:8083