spring:
  application:
    name: gateway-service
server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/ 
zuul:
  prefix: /api
  routes:
    eurika-client:
      path: /eureka-client/**
      serviceId: eureka-client
    feign-client:
      path: /feign-client/**
      serviceId: feign-client