spring:
  application:
    name: gateway-service
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
zuul:
  prefix: /api
  routes:
    eurika-client:
      path: /eureka-client/**
      serviceId: eureka-client
    feign-client:
      path: /feign-client/**
      serviceId: feign-client